### ISSUE TITLE
모바일에서 랜딩 페이지가 스크린 height에 딱 맞지 않는 이슈

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#11]
## Todo
- [x] 랜딩 페이지에서 screen height을 체크하는 부분 스크립트 추가 또는 수정

## Requirements
- [x] 모바일에서도 첫 화면 진입 시 이미지가 세로에 맞게 보여야 함
- [x] 화면의 중앙에 글자들이 정렬되어야 함
