### ISSUE TITLE
kagglebreak.com 메인에 CoC, 스터디 규칙 추가

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#13]
## Todo
- [x] admin에 CoC 데이터 입력
- [x] `index`  페이지에 스터디 규칙(준수사항) 추가
- [x] (모바일에서) width가 일정 크기보다 작아지면 세로로 재배열되도록 추가

## Requirements
- [x] 기능 상 문제가 없어야 함
- [x] PC와 모바일에서 view가 깨지지 않아야 함
