### ISSUE TITLE
커뮤니티 공홈 메인에 기존 캐글 참여내역 컨텐츠 넣기

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#15]
## Todo
- [x] 메인 페이지에 바로 넣을지, 별도의 페이지를 생성하고 메뉴를 연결할 지 결정
- [x] 모델 생성
- [x] 데이터 입력
- [x] 메인 메이지에 넣거나 연결

## Requirements
- [x] 기능상의 문제가 없어야 함
- [x] 미관상 문제가 없어야 함
- [x] pc와 모바일 모두에서 깨지지 않아야 함

**Comment by lynn-hong** [comment]
- archive 탭에 연결시켜 둠
