### ISSUE TITLE
model 내의 일부 필드에서 긴 텍스트 넣을 수 없는 문제 해결

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#2]
## Todo
- [x] model.py 에서 기존 45이던 길이를 255로 확장: members > interest
- [x] model.py 에서 기존 45이던 길이를 255로 확장: members > introduction

## Requirement
- [x] 긴 텍스트가 제대로 입력되는지 확인
