### ISSUE TITLE
각 페이지의 오타 및 마이너 디자인 수정

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#22]
## Todo
- [x] CoC의 문구 변경 및 오타 수정
- [x] sponsorship guideline 문구 변경
- [x] 메인 페이지에서 #speakers anchor로 갔을 떄 상단에 공간이 적은 부분 수정
