### ISSUE TITLE
공지사항을 띄울 수 있는 기능 추가

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#24]
## Todo
- [x] 어떤 형태로 공지사항을 띄울 것인가 결정
- [x] 공지사항을 볼 수 있는 곳 추가

## Requirements
- [x] 기능상에 문제가 없어야 함
- [x] 디자인이 자연스러워야 함

**Comment by lynn-hong** [comment]
완료하여 close
