### ISSUE TITLE
후원사를 레벨별로 띄우도록 변경

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#25]
## Todo
- [x] 후원 등급에 따라 후원사가 각기 다른 줄에 놓이도록 변경
- [x] 높은 후원 등급은 로고가 더 커지게 배치
- [x] 직접 지정한 순서에 따라 후원사가 ordering 되도록 변경
