### ISSUE TITLE
랜딩 첫화면의 문구 순서를 변경 가능하도록 함(Home model)

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#33]
## Todo
- [x] 모델에 order 추가
- [x] admin view에 반영
- [x] order에 따라 순서 정렬하도록 view 변경
- [x] 미관상 문제와 버그가 없는지 체크
