### ISSUE TITLE
캐글데이즈 행사 정보 추가하여 업데이트

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#35]
# todo
- [x] 랜딩 페이지 사진 변경
- [x] index 페이지에 배너 영역 추가
- [x] 캐글데이즈 사진으로 썸네일 변경
