### ISSUE TITLE
meetup 관련 페이지 추가

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#38]
## todo
- [x] 발표자 모집 내용 추가
- [x] meetup 일정, 발표자료 업로드할 공간 추가
- [x] 디자인적, 기능적으로 문제가 없어야 함

**Comment by lynn-hong** [comment]
- 1차 완료되어 배포하였으므로 close
