### ISSUE TITLE
상시 sponsor와 행사별 sponsor 분리

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#4]
## Todo
- [x] 스폰서 정보 입력
- [x] 상시 스폰서에 정보 표기
- [x] kagglebreak.com에는 상시 스폰서만 표기되도록 함
- [ ] 상시 스폰서에 동일한 내용 반복되는 것 수정
- [x] databreak2018 홈페이지에 행사별 스폰서 표기되도록 함
