### ISSUE TITLE
캐글데이즈 특화 디자인 요소들 디폴트로 복귀

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#41]
## todo
- [x] 기본 썸네일 변경
- [x] 랜딩 페이지 이미지 변경
- [x] base의 공지사항 팝업 문구 변경
- [x] index에 있던 배너 밋업 탭 내로 이동

**Comment by lynn-hong** [comment]
완료되어 close
