### ISSUE TITLE
event 별 스폰서, url, 키워드를 별도 지정할 수 있도록 모델 변경

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#42]
## todo
- [x] EventSponsor 모델 추가
- [x] EventUrl 모델 추가
- [x] EventKeyword 모델 추가
- [x] admin에 보여지도록 추가
- [x] 밋업 탭에 적절히 연결

**Comment by lynn-hong** [comment]
완료되어 close
