### ISSUE TITLE
페이지별로 썸네일과 페이지 이름이 자동 변경되도록 함

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#43]
## todo
- [x] default 썸네일 제작
- [x] meetup 썸네일 제작
- [x] 썸네일과 페이지 제목을 저장할 수 있는 모델 추가
- [x] 페이지별로 썸네일이 다르게 변경되도록 함
- [x] 페이지별로 페이지 제목이 다르게 변경되도록 함

## requirements
- [x] 기능상의 문제가 없어야 함

**Comment by lynn-hong** [comment]
완료되어 close
