### ISSUE TITLE
coc, about 등 자잘한 모델들 operation으로 통폐합

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#46]
## todo
- [ ] coc, about의 컨텐츠 operation에 입력
- [ ] view, template에서 참조하는 위치 변경
- [ ] 기존의 coc, about 모델 삭제
