### ISSUE TITLE
유투브 비디오 링크 저장할 수 있도록 변경

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#49]
## todo
- [x] model에 material_type 수정
- [x] admin 속성 추가
- [x] view에 youtube 아이콘 추가하고 링크 연결

**Comment by lynn-hong** [comment]
- 완료되어 close
