### ISSUE TITLE
model에서 sponsor level 추가

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#5]
## Todo
- [x] `models.py`에서 sponsor level 추가
- [x] 기존 스폰서들 레벨 정보 추가
- [x] admin에서 보이도록 수정
