### ISSUE TITLE
5월 밋업 종료에 따른 컨텐츠 수정, 마이너한 디자인 수정 등

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#54]
## todo
- [x] index 페이지에서 가입자 수 counter 숫자 수정
- [x] welcome 메시지 수정
- [x] 랜딩 페이지 이미지 변경

**Comment by lynn-hong** [comment]
이슈 해결하여 close
