### ISSUE TITLE
base, children 템플릿으로 분할

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#7]
## Todo
- [x] `base.html` 템플릿 생성
- [x] `index.html`을 제외한 `speech.html` 등 작은 페이지 inherit 되도록 함
- [x] `index.html`도 `base.html`을 상속하도록 변경
- [x] custom `context_processors.py` 생성하고 여기에서 footer에 들어갈 variable들 받아오도록 함
- [x] `settings.py`에서 context_processor 연결

## Requirement
- [x] `base.html`에 queryset을 통해 넘어오는 variable들이 제대로 표기되어야 함
- [x] 모든 페이지에서 기능상에 문제가 없어야 함
