### ISSUE TITLE
별도의 coc, sponsorship html 파일 생성

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/kagglebreak#8]
## Todo
- [x] `coc.html` 파일 추가
- [x] `sponsorhip.html` 파일 추가
- [x] 메뉴와 연결되도록 `urls.py 수정
- [x] view에 추가
- [x] css 조정

## Requirement
- [x] 기능상에 문제가 없어야 함
- [x] 디자인이 자연스러워야 함
